# Generated by Django 3.0.8 on 2020-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UN', 'Unpublished'), ('PB', 'Published')], default='UN', max_length=2)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'index_together': {('status', 'title')},
            },
        ),
    ]
