# Generated by Django 3.0.8 on 2020-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
